// Generated by Wrangler on Thu Sep 05 2024 05:36:43 GMT+0530 (India Standard Time)
// by running `wrangler types`

interface Env {
  GITHUB_ALERT_BOT_KV: KVNamespace;
  DEV_ROOM_URL: string;
  PROD_ROOM_URL: string;
  GITHUB_API_TOKEN: string;
}
